# Generated by Django 5.2.7 on 2025-10-22 23:42

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrator',
            managers=[
                ('objects', accounts.models.AdministratorManager()),
            ],
        ),
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9()+\\-\\s]{8,20}$', 'Telefone inválido')], verbose_name='Telefone'),
        ),
    ]
