# Generated by Django 5.2.1 on 2025-11-18 17:02

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.employee',),
            managers=[
                ('objects', accounts.models.AdministratorManager()),
            ],
        ),
    ]
