# Generated by Django 5.2.1 on 2025-10-23 23:05

import core.reports.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_reports', '0003_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=core.reports.storage.AttachmentStorage(), upload_to=''),
        ),
    ]
